resource_group_name = "__rgname__"
location            = "__location__"
db_name             = "__db_name__"
sql_admin_username  = "__sql_admin_username__"
sql_password        = "__sql_password__"

# resource_group_name = "myapp"
# location            = "westus"
# db_name             = "mydatabase9317"
# sql_admin_username  = "mradministrator"
# sql_password        = "P@ssw0rd12345!"
